css homepage
francoo-trainer/rulea-bootcamp-questionary pull request #2
Opened 2023-02-23 01:57 UTC by francoo-trainer

styles are added on homepage

2023-02-27 15:09 UTC, Theweeksad requested changes
please fix main class

2023-02-27 15:09 UTC, Theweeksad commented on css/homepage.css
> +main {
don't use tags, use a main class instead, e.g. (.main)

2023-02-28 13:46 UTC, Theweeksad approved these changes
nice work!!!

2023-02-28 16:48 UTC, Theweeksad approved these changes
all ready, I think all ready to merge

2023-03-01 12:59 UTC, johanmendezb approved these changes
good job

2023-03-01 16:17 UTC, ripsamuel commented
Please attach ss of the layaout
good job

2023-03-02 14:16 UTC, merged